set quiet := true

alias b := build

cargo := require("cargo")
visualizer-build := cargo + " b -p visualizer --release --target wasm32-unknown-unknown"

[default]
[private]
default:
    {{ just_executable() }} -u --list --justfile {{ justfile() }}

# builds a project of choice among those with preset build configurations
build project:
    cd {{ justfile_directory() }}
    {{ if project == "visualizer" { visualizer-build } else { error("no project in the current directory matches " + project) } }}
